schema_version: 1.2.0
id: CVE-2021-45469
aliases: []
modified: 2022-01-14T07:15Z
published: 2021-12-23T19:15Z
details: In __f2fs_setxattr in fs/f2fs/xattr.c in the Linux kernel through 5.15.11,
  there is an out-of-bounds memory access when an inode has an invalid last xattr
  entry.
severity:
- type: CVSS_V3
  score: 7.8
- type: CVSS_V2
  score: 4.6
affected:
- package:
    name: fedora
    cpe: cpe:2.3:o:fedoraproject:fedora
- ranges:
  - type: GIT
    repo: https://git.kernel.org/pub/scm/linux/kernel/git/chao/linux.git
    events:
    - introduced: '0'
    - fixed: ?h=dev&id=5598b24efaf4892741c798b425d543e4bed357a1
- versions:
  - '34'
  - '35'
- database_specific:
    CWE:
    - CWE-125
    CVSS:
      Score: 7.8
      Severity: HIGH
      Code: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
references:
- type: ADVISORY
  url: https://security.netapp.com/advisory/ntap-20220114-0003/
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2021/12/25/1
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AK2C4A43BZSWATZWFUHHHUQF3HPIALNP/
- type: REPORT
  url: https://bugzilla.kernel.org/show_bug.cgi?id=215235
- type: FIX
  url: https://git.kernel.org/pub/scm/linux/kernel/git/chao/linux.git/commit/?h=dev&id=5598b24efaf4892741c798b425d543e4bed357a1
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QG7XV2WXKMSMKIQKIBG5LW3Y3GXEWG5Q/
