schema_version: 1.2.0
id: CVE-2018-12565
aliases: []
modified: 2019-09-18T21:00Z
published: 2018-06-19T05:29Z
details: An issue was discovered in Linaro LAVA before 2018.5.post1. Because of use
  of yaml.load() instead of yaml.safe_load() when parsing user data, remote code execution
  can occur.
severity:
- type: CVSS_V3
  score: 8.8
- type: CVSS_V2
  score: 6.5
affected:
- package:
    name: lava
    cpe: cpe:2.3:a:linaro:lava
- ranges:
  - type: GIT
    repo: https://git.linaro.org/lava/lava.git
    events:
    - introduced: '0'
    - fixed: 583666c84ea2f12797a3eb71392bcb05782f5b14
- database_specific:
    CWE:
    - CWE-20
    CVSS:
      Score: 8.8
      Severity: HIGH
      Code: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
references:
- type: ADVISORY
  url: https://www.debian.org/security/2018/dsa-4234
- type: FIX
  url: https://git.linaro.org/lava/lava.git/commit/?id=583666c84ea2f12797a3eb71392bcb05782f5b14
