schema_version: 1.2.0
id: CVE-2021-4118
aliases: []
modified: 2022-01-04T16:27Z
published: 2021-12-23T18:15Z
details: pytorch-lightning is vulnerable to Deserialization of Untrusted Data
severity:
- type: CVSS_V3
  score: 7.8
- type: CVSS_V2
  score: 6.8
affected:
- package:
    name: pytorch_lightning
    cpe: cpe:2.3:a:pytorchlightning:pytorch_lightning
- ranges:
  - type: GIT
    repo: https://github.com/pytorchlightning/pytorch-lightning
    events:
    - introduced: '0'
    - fixed: 62f1e82e032eb16565e676d39e0db0cac7e34ace
- database_specific:
    CWE:
    - CWE-502
    CVSS:
      Score: 7.8
      Severity: HIGH
      Code: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
references:
- type: FIX
  url: https://github.com/pytorchlightning/pytorch-lightning/commit/62f1e82e032eb16565e676d39e0db0cac7e34ace
- type: WEB
  url: https://huntr.dev/bounties/31832f0c-e5bb-4552-a12c-542f81f111e6
