schema_version: 1.2.0
id: CVE-2016-10127
aliases: []
modified: 2017-03-08T01:07Z
published: 2017-03-03T15:59Z
details: PySAML2 allows remote attackers to conduct XML external entity (XXE) attacks
  via a crafted SAML XML request or response.
severity:
- type: CVSS_V3
  score: 9.0
- type: CVSS_V2
  score: 6.8
affected:
- package:
    name: pysaml2
    cpe: cpe:2.3:a:pysaml2_project:pysaml2
- ranges:
  - type: GIT
    repo: https://github.com/rohe/pysaml2
    events:
    - introduced: '0'
    - fixed: 6e09a25d9b4b7aa7a506853210a9a14100b8bc9b
- database_specific:
    CWE:
    - CWE-611
    CVSS:
      Score: 9.0
      Severity: CRITICAL
      Code: CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H
references:
- type: FIX
  url: https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b
- type: WEB
  url: http://www.securityfocus.com/bid/95376
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2017/01/19/5
- type: REPORT
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716
- type: REPORT
  url: https://github.com/rohe/pysaml2/issues/366
- type: WEB
  url: https://github.com/rohe/pysaml2/pull/379
