schema_version: 1.2.0
id: CVE-2020-15720
aliases: []
modified: 2020-07-23T16:33Z
published: 2020-07-14T14:15Z
details: In Dogtag PKI through 10.8.3, the pki.client.PKIConnection class did not
  enable python-requests certificate validation. Since the verify parameter was hard-coded
  in all request functions, it was not possible to override the setting. As a result,
  tools making use of this class, such as the pki-server command, may have been vulnerable
  to Person-in-the-Middle attacks in certain non-localhost use cases. This is fixed
  in 10.9.0-b1.
severity:
- type: CVSS_V3
  score: 6.8
- type: CVSS_V2
  score: 4.0
affected:
- package:
    name: dogtagpki
    cpe: cpe:2.3:a:dogtagpki:dogtagpki
- ranges:
  - type: GIT
    repo: https://github.com/dogtagpki/pki
    events:
    - introduced: '0'
    - fixed: 50c23ec146ee9abf28c9de87a5f7787d495f0b72
- database_specific:
    CWE:
    - CWE-295
    CVSS:
      Score: 6.8
      Severity: MEDIUM
      Code: CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:N
references:
- type: FIX
  url: https://github.com/dogtagpki/pki/commit/50c23ec146ee9abf28c9de87a5f7787d495f0b72
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1855273
- type: WEB
  url: https://github.com/dogtagpki/pki/compare/v10.9.0-a2...v10.9.0-b1
