schema_version: 1.2.0
id: CVE-2021-29562
aliases:
- GHSA-36vm-xw34-x4pj
modified: 2021-05-18T20:07Z
published: 2021-05-14T20:15Z
details: TensorFlow is an end-to-end open source platform for machine learning. An
  attacker can cause a denial of service by exploiting a `CHECK`-failure coming from
  the implementation of `tf.raw_ops.IRFFT`. The fix will be included in TensorFlow
  2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3,
  TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported
  range.
severity:
- type: CVSS_V3
  score: 5.5
- type: CVSS_V2
  score: 2.1
affected:
- package:
    name: tensorflow
    cpe: cpe:2.3:a:google:tensorflow
- ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    events:
    - introduced: '0'
    - fixed: 1c56f53be0b722ca657cbc7df461ed676c8642a2
- database_specific:
    CWE:
    - CWE-617
    CVSS:
      Score: 5.5
      Severity: MEDIUM
      Code: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
references:
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/1c56f53be0b722ca657cbc7df461ed676c8642a2
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-36vm-xw34-x4pj
