schema_version: 1.2.0
id: CVE-2021-29543
aliases:
- GHSA-fphq-gw9m-ghrv
modified: 2021-07-27T17:26Z
published: 2021-05-14T20:15Z
details: TensorFlow is an end-to-end open source platform for machine learning. An
  attacker can trigger a denial of service via a `CHECK`-fail in `tf.raw_ops.CTCGreedyDecoder`.
  This is because the implementation(https://github.com/tensorflow/tensorflow/blob/1615440b17b364b875eb06f43d087381f1460a65/tensorflow/core/kernels/ctc_decoder_ops.cc#L37-L50)
  has a `CHECK_LT` inserted to validate some invariants. When this condition is false,
  the program aborts, instead of returning a valid error to the user. This abnormal
  termination can be weaponized in denial of service attacks. The fix will be included
  in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow
  2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still
  in supported range.
severity:
- type: CVSS_V3
  score: 5.5
- type: CVSS_V2
  score: 2.1
affected:
- package:
    name: tensorflow
    cpe: cpe:2.3:a:google:tensorflow
- ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    events:
    - introduced: '0'
    - fixed: ea3b43e98c32c97b35d52b4c66f9107452ca8fb2
- database_specific:
    CWE:
    - CWE-617
    CVSS:
      Score: 5.5
      Severity: MEDIUM
      Code: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
references:
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-fphq-gw9m-ghrv
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/ea3b43e98c32c97b35d52b4c66f9107452ca8fb2
